### ISSUE TITLE
很抱歉，也许我是小白，但是这玩意部署在服务器上无法登录啊

### ISSUE THREAD

**Issue by ijuse** [x-dr/telegraph-Image#10]
输入`admin`并没有打开后台管理页面，也没有安装提示....

**Comment by ijuse** [comment]
![4539ae0ebb6c7a150322d.png](https://telegra.ph/file/4539ae0ebb6c7a150322d.png)

**Comment by ijuse** [comment]
前台是正常的
![af0a338d37e0f03646635.png](https://telegra.ph/file/af0a338d37e0f03646635.png)

**Comment by x-dr** [comment]
请看文档
