### ISSUE TITLE
[Support] 管理界面无法显示

### ISSUE THREAD

**Issue by zy111x** [x-dr/telegraph-Image#100]
![image](https://github.com/user-attachments/assets/460abbc3-21d3-46b4-ab51-eb309ce0e0f2)
我的管理界面不显示，出现这个是咋回事

**Comment by x-dr** [comment]
截图你的配置看看

**Comment by zy111x** [comment]
> 截图你的配置看看

![image](https://github.com/user-attachments/assets/8df39a8a-1971-4630-96c9-3266366c4e47)
哥你看咋回事

**Comment by x-dr** [comment]
> > 截图你的配置看看
> 
> ![image](https://private-user-images.githubusercontent.com/150530845/370677206-8df39a8a-1971-4630-96c9-3266366c4e47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjExODUsIm5iZiI6MTcyNzI2MDg4NSwicGF0aCI6Ii8xNTA1MzA4NDUvMzcwNjc3MjA2LThkZjM5YThhLTE5NzEtNDYzMC05NmM5LTMyNjYzNjZjNGU0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMDQxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzBiOTAxZmRlYjYzM2E4OTNiMzAyZTBmNjZmMjIzNjVjNDE0MDk2ZWM1OTdhMzI5ODBlZmM1NTQ4ZDhmOGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ycUUccvs4dmDZnweAezaXt2eR9mtmPrUxKklp3sRfp4) 哥你看咋回事

数据库配置了吗

**Comment by zy111x** [comment]
> > > 截图你的配置看看
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/150530845/370677206-8df39a8a-1971-4630-96c9-3266366c4e47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjExODUsIm5iZiI6MTcyNzI2MDg4NSwicGF0aCI6Ii8xNTA1MzA4NDUvMzcwNjc3MjA2LThkZjM5YThhLTE5NzEtNDYzMC05NmM5LTMyNjYzNjZjNGU0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMDQxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzBiOTAxZmRlYjYzM2E4OTNiMzAyZTBmNjZmMjIzNjVjNDE0MDk2ZWM1OTdhMzI5ODBlZmM1NTQ4ZDhmOGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ycUUccvs4dmDZnweAezaXt2eR9mtmPrUxKklp3sRfp4) 哥你看咋回事
> 
> 数据库配置了吗

![image](https://github.com/user-attachments/assets/690ef306-0c05-44ab-adcd-7e5016e1d5ab)

有了

**Comment by zy111x** [comment]
> > > 截图你的配置看看
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/150530845/370677206-8df39a8a-1971-4630-96c9-3266366c4e47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjExODUsIm5iZiI6MTcyNzI2MDg4NSwicGF0aCI6Ii8xNTA1MzA4NDUvMzcwNjc3MjA2LThkZjM5YThhLTE5NzEtNDYzMC05NmM5LTMyNjYzNjZjNGU0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMDQxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzBiOTAxZmRlYjYzM2E4OTNiMzAyZTBmNjZmMjIzNjVjNDE0MDk2ZWM1OTdhMzI5ODBlZmM1NTQ4ZDhmOGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ycUUccvs4dmDZnweAezaXt2eR9mtmPrUxKklp3sRfp4) 哥你看咋回事
> 
> 数据库配置了吗

明白了哥是我的问题，不小心删了库里的一个文件夹，重新配一下就好了
