### ISSUE TITLE
美团点评接口最新代码没有传上来吗，static的代码已经失效了

### ISSUE THREAD

**Issue by yisar** [x-dr/telegraph-Image#119]
如题

**Comment by xingfu111** [comment]
美团现在的入口处是美团创造者平台需要注册账号获取token才能上传的，网上有你自己改一下就可以用了。

**Comment by xingfu111** [comment]
> 如题

美团现在的入口处是美团创造者平台需要注册账号获取token才能上传的，网上有你自己改一下就可以用了。

**Comment by yisar** [comment]
好的谢谢哥，那就先不用了吧，因为俺发现美团的接口需要审核，不支持色图，啊哈哈

**Comment by xingfu111** [comment]
> 好的谢谢哥，那就先不用了吧，因为俺发现美团的接口需要审核，不支持色图，啊哈哈

tg也会疯号，58定期删图的，别的东西没有稳定的😁

**Comment by yisar** [comment]
米游社好像可以，俺一直在用，图片和视频，但是没封装接口
