### ISSUE TITLE
南方科技大学的cdn抓紧换了吧

### ISSUE THREAD

**Issue by coppea** [x-dr/telegraph-Image#14]
没法用，
![mirrors sustech edu cn_多地Ping值测试](https://github.com/x-dr/telegraph-Image/assets/86509331/413b6246-d0b0-436f-93d2-2780fe323381)

**Comment by x-dr** [comment]
我测试可用

![image](https://github.com/x-dr/telegraph-Image/assets/79109673/14ac1c5d-2fdf-499b-8c35-596fdfaa1bf6)

**Comment by coppea** [comment]
找到问题了，山东移动封了
