### ISSUE TITLE
求求作者+个超过5M可以压缩的功能吧

### ISSUE THREAD

**Issue by xiaochenhh** [x-dr/telegraph-Image#15]
+个超过5M可以压缩的功能吧，可选可不选的那种！！

**Comment by x-dr** [comment]
我有空看看

**Comment by xiaochenhh** [comment]
嘿嘿嘿感谢~麻烦啦~

x-dr ***@***.***> 于 2024年5月12日周日 19:35写道：

**Comment by x-dr** [comment]
把https://github.com/x-dr/telegraph-Image/blob/52d1b8a82e1e040dfd9ae4cbc03d32c641ffdbeb/asset/js/upload.js#L21   注释掉 ，然后根据需求加上这几个参数即可 。
![image](https://github.com/x-dr/telegraph-Image/assets/79109673/43d49d82-81bd-431a-800f-01f8783c06b0)

```javascript
    maxImageWidth: 200,   
    maxImageHeight: 150,    
    resizePreference: 'height',
    maxFileCount: 1,
    resizeImage: true,
    resizeIfSizeMoreThan: 1000,
  ```
具体说明可以看[bootstrap-fileinput ](https://plugins.krajee.com/file-input/plugin-options#minimageheight)的文档

**Comment by xiaochenhh** [comment]
感谢作者~ヾ ^_^♪麻烦啦~

x-dr ***@***.***> 于 2024年5月14日周二 00:47写道：
