### ISSUE TITLE
一些文件上传时为什么cloudflare报错：REEOR 1101？

### ISSUE THREAD

**Issue by 1212wuhu** [x-dr/telegraph-Image#17]
![image](https://github.com/x-dr/telegraph-Image/assets/84019418/1ede349a-6b65-4907-9264-0709bf115642)
如图所示

**Comment by x-dr** [comment]
因该是网络问题，超时了

**Comment by qingshuicn** [comment]
看后台错误提示脚本一场

**Comment by gitlayzer** [comment]
感觉最近的 CF 这图床项目有点危险，换 Vercel 部署它吧，挺稳定的
