### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by imokgood** [x-dr/telegraph-Image#2]
部署在Cloudflare成功，也自定义了域名，但是上传一直失败500错误，全局模式可以上传成功，自定义域名没有被墙，这是咋回事？

**Comment by imokgood** [comment]
还有，就算上传成功了，在admin后台也始终是空的，记录总数量: 0

**Comment by x-dr** [comment]
> 还有，就算上传成功了，在admin后台也始终是空的，记录总数量: 0

重新部署试试

**Comment by 308207109** [comment]
Enable JavaScript and cookies to continue
![image](https://github.com/user-attachments/assets/e3c776c5-eecc-421e-a734-b8e1e1f1d1cd)
自定义域名 cf直接拦截了
