### ISSUE TITLE
图床无法使用

### ISSUE THREAD

**Issue by hausen1012** [x-dr/telegraph-Image#22]
mirrors.sustech.edu.cn 挂了，导致图床无法使用

**Comment by x-dr** [comment]
> mirrors.sustech.edu.cn 挂了，导致图床无法使用

应该是你那个地区的限制的原因，我找个时间看看找个稳定的cdn替换掉它  如果你有稳定的也欢迎提个pr

**Comment by hausen1012** [comment]
这会好了，今天上午那会访问不了，辛苦了大佬

**Comment by hausen1012** [comment]
不能直接放本地文件吗？

**Comment by woshichenghaibo** [comment]
加上前置图片压缩功能？
