### ISSUE TITLE
后台删除图片报错：SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by shanglong2333** [x-dr/telegraph-Image#23]
1.后台删除图片报错：SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
2.可否请大佬设置个上传限制，不然被人滥用就难受了

**Comment by x-dr** [comment]
1 、后台删除图片报错？我没遇到这问题
测试：https://testimg.131213.xyz/
测试账号：admin
测试密码：admin

2、上传限制看看后续有空再加
