### ISSUE TITLE
能否做一个php版本

### ISSUE THREAD

**Issue by veip007** [x-dr/telegraph-Image#24]
目前图床的功能很实用，但也存在2个问题：
1.cf的额度限制
2.因为是cf，所以有的时候打开图床会因网络问题显示不正常(是网站不正常，不是图片),挂代理和直连都会有这个问题
3.不好设置密码访问。
若php版本的话就不存在以上问题

虽然我第三点已经在html设置了密码并加密，但这个仅限于小白进不去，高手还是随便进的。
希望作者能开发个php版本，毕竟php是世界上最好的语言

**Comment by x-dr** [comment]
绑定域名后cloudflare没额度没限制了，至于php的话cloudflare不支持，不能白嫖了，看后续有空整个服务器版吧
