### ISSUE TITLE
vercel是否可以支持后台管理？

### ISSUE THREAD

**Issue by 1715819** [x-dr/telegraph-Image#3]

**Comment by 1715819** [comment]
vercel分支似乎没有admin.html，具体如何修改呢？

**Comment by x-dr** [comment]
> vercel分支似乎没有admin.html，具体如何修改呢？

参考`functions` 文件夹的接口修改vercel分支的`api`文件夹

对应的api路径是`/api/xxx`

admin.html 直接复制过去修改一下就行
