### ISSUE TITLE
搭建完成后，上传照片正常，日志拉取正常，但是后台登录进去一个照片没有。

### ISSUE THREAD

**Issue by Vardven** [x-dr/telegraph-Image#31]
开启了API鉴黄，API审查也有记录，就是后台没有一张照片，前台也显示上传了0张照片。

**Comment by Vardven** [comment]
![截屏2024-06-23 下午2.34.59](http://photo.bbbp.tech/i/2024/06/23/nqn3e1.png)

**Comment by Vardven** [comment]
![截屏2024-06-23 下午2.36.40](http://photo.bbbp.tech/i/2024/06/23/nrqgsu.png)

**Comment by Vardven** [comment]
![截屏2024-06-23 下午2.38.08](http://photo.bbbp.tech/i/2024/06/23/nsgbvt.png)
![截屏2024-06-23 下午2.38.26](http://photo.bbbp.tech/i/2024/06/23/nsgc42.png)

**Comment by Vardven** [comment]
![截屏2024-06-23 下午2.39.22](http://photo.bbbp.tech/i/2024/06/23/nsyg55.png)

**Comment by androidcoderr** [comment]
我也发现了这个**BUG**

**Comment by Vardven** [comment]
> 我也发现了这个**BUG**

解决了吗，试了好多方法不行！

**Comment by x-dr** [comment]
你如何配置的？我使用没问题
后台配置
![](https://testimg.131213.xyz/file/99715973805f0a01b070e.png)



测试：https://testimg.131213.xyz/

测试账号：admin

测试密码：admin

**Comment by 2ipm1nd** [comment]
我也是，完全顯現不出IP跟圖片數量，後臺也都沒有記錄，但是圖片可以正常顯示

![螢幕快照 2024-06-28 19-04-12](https://github.com/x-dr/telegraph-Image/assets/43886416/d4ee9844-3f58-4254-90e4-205c5e4d7842)

**Comment by x-dr** [comment]
> 我也是，完全顯現不出IP跟圖片數量，後臺也都沒有記錄，但是圖片可以正常顯示
> 
> ![螢幕快照 2024-06-28 19-04-12](https://private-user-images.githubusercontent.com/43886416/344139972-d4ee9844-3f58-4254-90e4-205c5e4d7842.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzYyMzksIm5iZiI6MTcxOTU3NTkzOSwicGF0aCI6Ii80Mzg4NjQxNi8zNDQxMzk5NzItZDRlZTk4NDQtM2Y1OC00MjU0LTkwZTQtMjA1YzVlNGQ3ODQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDExNTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYTEwMTIyZjQzMTc3N2RiM2FmMjc5NmU2ZDcxM2UwMGJkNzlkZWJlYWUyMjJkOTE2ZjliYWUzZTc5MjUyYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.17XCAW2VSBvz7V5E6QSm1SkfkyB130qxmL8yn6qI1lY)
> 
> 設定了D1資料庫，但是沒設定鑑黃

IP得设置域名才会显示，后台没记录估计是没设置鉴黄的问题 我这两天修改一下

**Comment by androidcoderr** [comment]
> > > 我也是，完全顯現不出IP跟圖片數量，後臺也都沒有記錄，但是圖片可以正常顯示
> > > ![螢幕快照 2024-06-28 19-04-12](https://private-user-images.githubusercontent.com/43886416/344139972-d4ee9844-3f58-4254-90e4-205c5e4d7842.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzYyMzksIm5iZiI6MTcxOTU3NTkzOSwicGF0aCI6Ii80Mzg4NjQxNi8zNDQxMzk5NzItZDRlZTk4NDQtM2Y1OC00MjU0LTkwZTQtMjA1YzVlNGQ3ODQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDExNTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYTEwMTIyZjQzMTc3N2RiM2FmMjc5NmU2ZDcxM2UwMGJkNzlkZWJlYWUyMjJkOTE2ZjliYWUzZTc5MjUyYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.17XCAW2VSBvz7V5E6QSm1SkfkyB130qxmL8yn6qI1lY)
> > > 設定了D1資料庫，但是沒設定鑑黃
> > 
> > 
> > IP得设置域名才会显示，后台没记录估计是没设置鉴黄的问题 我这两天修改一下
> 
> 抱歉我是新手，請問一下**設置域名**是怎麼設定？因為我安裝完成之後 cloudflare 就給了我一個域名 `xxxxx.pages.dev` 我直接點了就能使用，我還需要怎麼做才能顯示IP呢？

先把一个你已拥有并且可托管到Cloudflare的Domain,无论是一级域名还是二级都可以, 然后托管到上面去, Pages点击添加自定义域, 然后输入已托管的域名或者在已托管的域名前面添加一个下一级域名, 随便起一个, 比如你的域名是123.com你就可以添加一个img.123.com, 如果你的域名是456.123.com, 你就可以添加img.456.123.com以此类推, 类比即可.

**Comment by Vardven** [comment]
> > 我也是，完全顯現不出IP跟圖片數量，後臺也都沒有記錄，但是圖片可以正常顯示
> > 
> > ![螢幕快照 2024-06-28 19-04-12](https://private-user-images.githubusercontent.com/43886416/344139972-d4ee9844-3f58-4254-90e4-205c5e4d7842.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzYyMzksIm5iZiI6MTcxOTU3NTkzOSwicGF0aCI6Ii80Mzg4NjQxNi8zNDQxMzk5NzItZDRlZTk4NDQtM2Y1OC00MjU0LTkwZTQtMjA1YzVlNGQ3ODQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDExNTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYTEwMTIyZjQzMTc3N2RiM2FmMjc5NmU2ZDcxM2UwMGJkNzlkZWJlYWUyMjJkOTE2ZjliYWUzZTc5MjUyYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.17XCAW2VSBvz7V5E6QSm1SkfkyB130qxmL8yn6qI1lY)
> > 
> > 設定了D1資料庫，但是沒設定鑑黃
> 
> IP得设置域名才会显示，后台没记录估计是没设置鉴黄的问题 我这两天修改一下

我设置了剑皇，我发现TG和meituan上传了后台不显示，其他的显示。

**Comment by soeos** [comment]
重新部署一下就出来了
