### ISSUE TITLE
忠告: 谨防CF官方封杀! 需要在防滥用方面下功夫! 

### ISSUE THREAD

**Issue by androidcoderr** [x-dr/telegraph-Image#33]
我估计**CF官方**不会很乐意我们 _无限制_ 的 _白嫖_ 他们的资源!!! 所以**不容乐观** !!! 需要**多加小心** _项目安全性问题_ !!! 还有**谢谢大佬**的贡献!

**Comment by gitlayzer** [comment]
vercel 目前稳定
