### ISSUE TITLE
API上传

### ISSUE THREAD

**Issue by mt-altman** [x-dr/telegraph-Image#34]
有计划开放API上传吗
或者已经有了？怎么使用？

**Comment by mt-altman** [comment]
curl --location --request POST 'https://your.domain/upload' \
--form 'file=@"path/image.png"' \
--form 'fileId="1572420__E4_B8_8B_E8_BD_BD.png"'

**Comment by gitlayzer** [comment]
获取 payload 参数然后构造一个请求就可以了
