### ISSUE TITLE
用pages.dev登录过后台正常，绑定自定义域再登录就直接提示登录失败

### ISSUE THREAD

**Issue by awinds** [x-dr/telegraph-Image#35]
用pages.dev登录过后台正常，绑定自定义域再登录就直接提示登录失败，不弹出登录框

**Comment by androidcoderr** [comment]
请截图提交环境变量, KV空间, 域名绑定设置

> 用pages.dev登录过后台正常，绑定自定义域再登录就直接提示登录失败，不弹出登录框

**Comment by awinds** [comment]
可能是浏览器缓存的原因，换个浏览器就可以了
