### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by zyz1123** [x-dr/telegraph-Image#4]
超过30张图上传按钮不见了

**Comment by x-dr** [comment]
右边有滚动条吗？
![16179620e97495729d870.png](https://img1.131213.xyz/file/16179620e97495729d870.png)

**Comment by zyz1123** [comment]
这个问题缩放页面解决了。还有大佬能不能优化下排序，就是图片按顺序来上传(不管多少张)。。还有上传出错的话再上传的排序能不能也优化下。感谢。

**Comment by zyz1123** [comment]
刚页面缩放到最小，测试54张图并没有显示下面那排按钮。火狐浏览器。100%的话我这里一排显示4张图。
