### ISSUE TITLE
管理面板部分添加单击按钮或者单击列表能够弹出上传时候的链接部分

### ISSUE THREAD

**Issue by soeos** [x-dr/telegraph-Image#43]
建议在管理面板部分(图1)添加单击按钮或者单击列表能够弹出上传时候的链接部分(如图2)，方便使用
![图1](https://github.com/user-attachments/assets/07a1a1fe-7a8d-4926-aed0-4dec3bdd528b)
![图2](https://github.com/user-attachments/assets/867eea33-0f90-42ac-9be4-a8ec28135718)

**Comment by x-dr** [comment]
这几天nextjs重新写了,加了弹出上传时候的链接部分，不过还没写完；
体验：
[https://telegraph-image-e49.pages.dev/](https://telegraph-image-e49.pages.dev/)
账号：admin
密码：admin

![28b08e2bdd908814f15de.png](https://img1.131213.xyz/file/28b08e2bdd908814f15de.png)

**Comment by soeos** [comment]
挺不错的，不过建议再加一个切换图片的功能，单击l两个按钮，可以实现快速切换
![image](https://github.com/user-attachments/assets/641426b8-24b8-4c77-8a5a-fa684c3418be)
