### ISSUE TITLE
vercel部署无法上传

### ISSUE THREAD

**Issue by sucooer** [x-dr/telegraph-Image#46]
使用vercel部署的上传不了，main和dev都无法上传
![](https://telegraph-image-2yc.pages.dev/file/1252388ccb24c2def16c5.png)

**Comment by x-dr** [comment]
main和dev分支兼容vercel

**Comment by sucooer** [comment]
> main和dev分支不兼容vercel

那dev分支该怎么部署？

**Comment by x-dr** [comment]
> > main和dev分支不兼容vercel
> 
> 那dev分支该怎么部署？

等我更新

**Comment by x-dr** [comment]
已更新
