### ISSUE TITLE
咨询个问题，上传的图片和视频文件。最终是存储在哪里的？

### ISSUE THREAD

**Issue by wnpllrzodiac** [x-dr/telegraph-Image#48]
cf的D1 应该只提供了文件metadata的存储吧。没看到二进制数据。
难道 telegraph提供了一个无限大的存储空间？
但是这样怎么保证这个空间的数据不被删除？

```
https://mypic.exmaple.com/file/xxxxxx.jpg
https://i3.wp.com/telegra.ph/file/xxxxx.jpg
https://telegra.ph/file/xxxxx.jpg
```
这几个图片存在同一个地方通过CNAME跳转的, 还是存了三份？

**Comment by shidang233** [comment]
图片实际是存储在telegra.ph的，因为telegra.ph国内无法访问，所以需要cf来进行反向代理

**Comment by wnpllrzodiac** [comment]
他们又删除策略吗？如果图片上传到那里，不知道多久会失效。是不是只能当临时文件用，随时会无效

**Comment by 0x032c** [comment]
> 图片实际是存储在telegra.ph的，因为telegra.ph国内无法访问，所以需要cf来进行反向代理

能增加个功能改成存放到cf的R2里面吗？
