### ISSUE TITLE
首页“你访问本站的IP是：”

### ISSUE THREAD

**Issue by standee2023** [x-dr/telegraph-Image#5]
你访问本站的IP是：这个代码在哪里加啊

**Comment by x-dr** [comment]
> 你访问本站的IP是：这个代码在哪里加啊

已经更新好了，更新最新版本就有了

**Comment by standee2023** [comment]
太棒了

**Comment by dishao123** [comment]
> > 你访问本站的IP是：这个代码在哪里加啊
> 
> 已经更新好了，更新最新版本就有了

请问使用模板仓库部署的，怎么更新？

**Comment by standee2023** [comment]
> > > 你访问本站的IP是：这个代码在哪里加啊
> > 
> > 
> > 已经更新好了，更新最新版本就有了
> 
> 请问使用模板仓库部署的，怎么更新？

打开你的模板仓库，有个“Sync fork"下拉框，打开后更新就可以了
