### ISSUE TITLE
严重bug，默认反向代理所有图片地址导致无法拉黑和删除！

### ISSUE THREAD

**Issue by shidang233** [x-dr/telegraph-Image#51]
我上传了一张黄色图片鉴黄API没检测到我去后台删除了（换了个浏览器还是可以打开），然后在list里也删除了一下记录，刷新一下list页面又回来了（我又去d1数据库查看表里的映射数据发现那张图片还在表里面），后台已删除，list页删除了刷新一下页面又回来了，D1数据库里的表还在

再加一条，图床好像不会按照d1数据库的表跳转而是不管是什么图片链接，不管存在D1与否都会显示（默认反代所有地址不会按照D1数据库的记录走）
比如我在我的图床上上传了一张图片保证未在作者的测试图床上传过但也可以显示。
简化，默认反向代理所有图片不跟随D1的数据表走，间歇性导致了拉黑和删除无法使用！
https://img.131213.xyz/file/b5ec60d715fedb7c9f1a2.png

**Comment by x-dr** [comment]
程序重写了，重新部署最新的看看

**Comment by shidang233** [comment]
emmm...部署了，访问404，浏览器白屏我的地址是
https://yunr.us.kg/
部署的默认地址是
https://img-e4x.pages.dev/

**Comment by shidang233** [comment]
访问不了，开启了后台管理变量也配置了
![Screenshot_20240806_112749_org mozilla firefox](https://github.com/user-attachments/assets/bf22a098-2620-4d2b-b7b6-b930c9c753ae)

https://yunr.us.kg/
https://img-e4x.pages.dev/

**Comment by x-dr** [comment]
> 访问不了，开启了后台管理变量也配置了 ![Screenshot_20240806_112749_org mozilla firefox](https://private-user-images.githubusercontent.com/79011008/355301609-bf22a098-2620-4d2b-b7b6-b930c9c753ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTU3MTksIm5iZiI6MTcyMjkxNTQxOSwicGF0aCI6Ii83OTAxMTAwOC8zNTUzMDE2MDktYmYyMmEwOTgtMjYyMC00ZDJiLWI3YjYtYjkzMGM5Yzc1M2FlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAzMzY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTZkY2YzZjM5MDE3ZWZlYzg3ZjE3Y2E1YzI1YmZiMmRjNjliNTM0NDIwNDliNTNmY2I2MTlhOGVlNjNhZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OkDv-ZcICaY0Ybc7UwqzyQEmdDfwicyN79P5t-1K5uM)
> 
> https://yunr.us.kg/ https://img-e4x.pages.dev/
> 
> 构建日志 Uploading img.07af5037-ea0d-4c31-b8f4-06b453643672.txt…


看步骤7

**Comment by shidang233** [comment]
啊这，忘了看下面的，对不起🧎，可以访问了但是后台开启限制访问刷新一下页面会自动关掉是什么原因？（自动关闭之后可以访问也提示关闭成功了）
https://yunr.us.kg/
账号yunshuang
密码imgyunshuang141
我用的是via浏览器

**Comment by x-dr** [comment]
不知道什么回事

> 啊这，忘了看下面的，对不起🧎，可以访问了但是后台开启限制访问刷新一下页面会自动关掉是什么原因？（自动关闭之后可以访问也提示关闭成功了） 我这次看完了步骤 https://yunr.us.kg/ 账号yunshuang 密码imgyunshuang141 我用的是via浏览器

我测试了2次 没问题  ，你重新部署试试

**Comment by shidang233** [comment]
我部署三次了。。。还是不行

**Comment by x-dr** [comment]
> PROXYALLIMG设置成false

你从第一步重新开始部署看看

**Comment by shidang233** [comment]
可以禁止访问图片了，但是后台的按钮还是开了以后只要刷新页面就自动关闭（不会影响阻止访问的图片继续阻止）解开阻止访问则需要再次点亮按钮然后再关闭按钮。
如果一个浏览器或页面打开了阻止访问，用另一个浏览器或者新开一个标签页再打开后台按钮则是关闭状态不会跟随变动

**Comment by x-dr** [comment]
https://testimg.131213.xyz/

测试账号：admin

测试密码：admin



我部署的没问题，你的这个问题好奇怪

**Comment by shidang233** [comment]
我也是一脸懵（用你的按钮都正常），先这样吧。。。
