### ISSUE TITLE
自定义域名加速麻烦给加回吧

### ISSUE THREAD

**Issue by coppea** [x-dr/telegraph-Image#53]
>  const getImgUrl = (url) => {
>      const customDomain = "https://your-custom-domain.com"; // 替换为你的自定义域名
 >     if (url.startsWith("/file/")) {
 >         return `${customDomain}/api${url}`; // 使用自定义域名
 >     } else {
>          return url; // 如果不是以"/file/"开头，则返回原始URL
>      }
>  };

我这么设置的，但是不生效

**Comment by x-dr** [comment]
已更新，添加一个`CUSTOM_DOMAIN` 环境变量就行

![image.png](https://img.131213.xyz/api/file/1d02c1917240d8762b077.png)
