### ISSUE TITLE
新版本反馈：后台无法删除照片，切换到日志页后是空白的

### ISSUE THREAD

**Issue by imyaer** [x-dr/telegraph-Image#54]
后台登录以后没有删除照片的选项了，并且切换到日志页后也是空白，数据没有存储

**Comment by x-dr** [comment]
删除照片的选项我周末看看  有空再加上；日志页空白不应该啊，你是怎样设置的

**Comment by imyaer** [comment]
我就是按照教程来的，开始我以为我设置不对，我后来从大佬你的演示网站也上传了一张照片，日志也是没有，但是数据里面有

**Comment by imyaer** [comment]
f991edc3374d072e82378.jpg 看一下这一张，我发现一个问题，好像有点问题，我通过自定义域传的照片没有日志，但是通过默认的那个网址有，不过延时很高，我早上传的，下午才出来日志

**Comment by x-dr** [comment]
> f991edc3374d072e82378.jpg 看一下这一张，我发现一个问题，好像有点问题，我通过自定义域传的照片没有日志，但是通过默认的那个网址有，不过延时很高，我早上传的，下午才出来日志

自定义是没日志的，延迟应该不会有的 缓存问题吧

**Comment by imyaer** [comment]
嗯 原来老版本就通过list访问没问题，不影响使用

**Comment by a39353678** [comment]
1.后台打开图片限制访问，还是能访问
2.后台没有删除图片选项，测试鉴黄api上传的限制级图片想删除都删除不了，有点怕怕

**Comment by cuteys** [comment]
佬，后台没有删除选项有空修一下呗

**Comment by x-dr** [comment]
@a39353678 @cuteys @imyaer  已更新删除照片
