### ISSUE TITLE
按照步骤按照以后还是报错，请问这是什么问题呢？

### ISSUE THREAD

**Issue by leaflyingl** [x-dr/telegraph-Image#56]
<img width="760" alt="1723458899906" src="https://github.com/user-attachments/assets/919f1637-63c7-4b6b-b142-52f86176c520">

**Comment by sampan79** [comment]
你是怎么解决的？
那个环节出错了？

**Comment by sampan79** [comment]
我自己的问题解决了。以下这个没有配置
设置兼容性标志，前往后台依次点击设置->函数->兼容性标志->配置生产兼容性标志 填写 nodejs_compat
