### ISSUE TITLE
大佬您好 之前部署了您的老版本界面那个 两个月前

### ISSUE THREAD

**Issue by shaoyouvip** [x-dr/telegraph-Image#57]
大佬您好 之前部署了您的老版本界面那个 两个月前 现在看到您的项目更新了， 我该如何更新操作 才能保留我的图片数据

**Comment by shidang233** [comment]
随便更新咯，图片数据不是保留在cf服务器的，反向映射表也是存在D1数据库的你只需要把项目重新获取一下重试部署就行
