### ISSUE TITLE
更新最新的项目后上传图片 显示有问题

### ISSUE THREAD

**Issue by shaoyouvip** [x-dr/telegraph-Image#58]
![image](https://github.com/user-attachments/assets/5175a255-b16b-4e3e-ae74-df99f54569e6)

更新最新的项目后  上传图片 显示有问题

**Comment by shidang233** [comment]
挂个梯子试试能不能成功访问图片如果可以的话应该是没加载出来

**Comment by shidang233** [comment]
那应该是当时没加载出来吧（毕竟cf对中国大陆不太友好），我今天刚更新的部署可以预览（我套了个优选域名），你可以挂着梯子再上传一张图大概率是可以预览的。（如果可以预览了就直接关单吧）

**Comment by shidang233** [comment]
腾讯的接口就不要挂梯子了（更慢。。。），你可以用TG的接口试试能不能浏览（逻辑是差不多的，至于为什么会自动下载而不是预览我也不知道），你若是知道什么是加速域名的话你可以配置下变量（我是直接套了一个cf的优选IP）
