### ISSUE TITLE
我想问一下TG的相关变量有什么用？

### ISSUE THREAD

**Issue by shidang233** [x-dr/telegraph-Image#59]
想问一下TG的相关变量有什么用
TG_CHAT_ID
和
TG_BOT_TOKEN
的变量
我也有TG想问问这两个变量加上去有什么功能？

**Comment by shidang233** [comment]
怎么用呀，配置完了两个变量上传了一张图片一点反应没有

**Comment by shidang233** [comment]
作者啊，回复下吧！

**Comment by x-dr** [comment]
把图片、文件上传到tg频道
