### ISSUE TITLE
IPv6地址太长导致手机上显示问题

### ISSUE THREAD

**Issue by shidang233** [x-dr/telegraph-Image#60]
IPv6地址太长导致显示问题。
手机：华为畅享10plus
项目的测试图床也是一样
![Screenshot_20240817_141433_org mozilla firefox](https://github.com/user-attachments/assets/88b0334e-99b7-4746-8a8e-a197701121a5)
项目的测试图床
![Screenshot_20240817_141642_org mozilla firefox](https://github.com/user-attachments/assets/a9d994cd-3c6f-445e-a858-686fe85bdc71)

**Comment by Boring1998** [comment]
我用via游览器界面正常
