### ISSUE TITLE
无法使用TG机器人的功能

### ISSUE THREAD

**Issue by shidang233** [x-dr/telegraph-Image#63]
配置好了两个TG机器人变量（新建了个空白机器人）无法将图片上传到TG频道或群组

**Comment by x-dr** [comment]
按教程走一般没问题

**Comment by shidang233** [comment]
按照教程走完了botkey和频道ID都写上了不行。。。

**Comment by x-dr** [comment]
> 按照教程走完了botkey和频道ID都写上了不行。。。

设置bot为管理员  设置了吗？

**Comment by shidang233** [comment]
嗯嗯，是管理员

**Comment by x-dr** [comment]
你提供的信息无法知道什么问题

**Comment by shidang233** [comment]
那咋办，就是填完两个变量就跟没填一样机器人一点反应没有

**Comment by x-dr** [comment]
> 那咋办，就是填完两个变量就跟没填一样机器人一点反应没有

你提供的信息无法知道什么问题，无法解决
