### ISSUE TITLE
PC 上无法显示播放视频

### ISSUE THREAD

**Issue by shulng** [x-dr/telegraph-Image#65]
在 PC 上无法显示播放视频
![image](https://github.com/user-attachments/assets/337d7be9-9ec3-4e90-8b6e-53732caed7d2)

但在手机上可以显示
![qq_pic_merged_1724229317238](https://github.com/user-attachments/assets/5dbd5160-ecdb-4b91-98da-90a4d053d838)
![qq_pic_merged_1724229308021](https://github.com/user-attachments/assets/8d60e0e7-74e1-4dee-9cf1-c6994185ad29)

**Comment by wnpllrzodiac** [comment]
视频链接发一下，估计不能解码。

**Comment by shulng** [comment]
> 视频链接发一下，估计不能解码。

https://two.shulng.us.kg/file/c83e69ddc8ed6a245bde7.mp4

**Comment by wnpllrzodiac** [comment]
Stream #0:0[0x1](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt470bg/bt470bg/bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 1246 kb/s, 30 fps, 30 tbr, 10000k tbn (default)

浏览器不支持h265(hevc)
