### ISSUE TITLE
对环境变量问题的请教

### ISSUE THREAD

**Issue by 88ok** [x-dr/telegraph-Image#66]
使用了模板，按照步骤配置。Tencent可以使用，但出现TG和TG-CHANNEL无法使用。有两个问题麻烦请教下
1.Tencent是上传在哪里？有什么限制吗？因为我没有配置tencent相关的key
2.按照步骤配置TG可以使用，但TG没看到上传的图片在哪里，同时TG-CHANNEL无法使用，已设置管理员。
麻烦大佬帮忙分析下，相关配置截图：
![image](https://github.com/user-attachments/assets/abaa48de-e003-4e9e-94c0-f5b7554eb023)
![image](https://github.com/user-attachments/assets/85c077c6-44b7-4b83-9b6e-9082a7ef0b98)
![image](https://github.com/user-attachments/assets/8c235682-65f6-4d4f-b9d0-fe8aa284b357)

麻烦大佬解释下。

THANKS.

**Comment by x-dr** [comment]
![image](https://github.com/user-attachments/assets/27c9a915-e9b1-4320-a764-85887db1e1a9)

是频道id，不是频道地址

**Comment by 88ok** [comment]
我修改成频道id重新部署依然不可以

> ![image](https://private-user-images.githubusercontent.com/79109673/359961063-27c9a915-e9b1-4320-a764-85887db1e1a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODk0MTgsIm5iZiI6MTcyNDI4OTExOCwicGF0aCI6Ii83OTEwOTY3My8zNTk5NjEwNjMtMjdjOWE5MTUtZTliMS00MzIwLWE3NjQtODU4ODdkYjFlMWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAxMTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNGNhMGIwYjkwOGNlMWY5NjQxM2YyM2U0MjkyNWZmMGE2ZmFhY2M3N2QzMThlOTg3Y2IzOWJiOWI5NGEzZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wn-RmalscvX03gDecKx3xxxuK9jG1xMaQU-mho8IqUU)
> 
> 是频道id，不是频道地址

**Comment by 88ok** [comment]
已解决，获取频道ID方法
https://api.telegram.org/bot【key】/sendMessage?chat_id=@【chat_name】&text=test

**Comment by x-dr** [comment]
> 已解决，获取频道ID方法 [https://api.telegram.org/bot【key】/sendMessage?chat_id=@【chat_name】&text=test](https://api.telegram.org/bot%E3%80%90key%E3%80%91/sendMessage?chat_id=@%E3%80%90chat_name%E3%80%91&text=test)

写了个bot 能更简单获取
[@VersaToolsBot](https://t.me/VersaToolsBot)
