### ISSUE TITLE
[Feature] 是否可以添加CFP_PASSWORD，但不起作用

### ISSUE THREAD

**Issue by hiing** [x-dr/telegraph-Image#71]
### 为防止滥用，是否可以使用 [cloudflare-pages-auth](https://github.com/Charca/cloudflare-pages-auth/) 的CFP_PASSWORD 进行变量控制？

但我复制了整个functions文件夹到项目中，并添加了环境变量，但不起作用。。

作者关于这个项目是详细说明：[Password Protection for Cloudflare Pages](https://dev.to/charca/password-protection-for-cloudflare-pages-8ma)

请组织者考虑  ：）

**Comment by x-dr** [comment]
本项目用的是`nextjs`+`next-auth`+`tailwindcss`,直接复制过来肯定是行不通的；
用`next-auth`加密码应该可以，但现在暂时没空，应该下周才有空修改了。

**Comment by x-dr** [comment]
已为tg channel接口添加访客验证
