### ISSUE TITLE
[Bug] 无链接

### ISSUE THREAD

**Issue by shulng** [x-dr/telegraph-Image#72]
部分后缀格式,上传后,会出现如下问题
![Screenshot_20240823_210813](https://github.com/user-attachments/assets/35d3421e-2e3b-4da5-9527-138dc95159e1)

例如.jpg或者其他的.xxx

**Comment by x-dr** [comment]
再次上传该图片看看会复现不，方便发一下该文件不

**Comment by shulng** [comment]
> 再次上传该图片看看会复现不，方便发一下该文件不

重新上传了一下
发现是tencent接口的问题。
换成默认的TG就不会出现了
