### ISSUE TITLE
[Bug] 鉴黄功能无效

### ISSUE THREAD

**Issue by heichaowo** [x-dr/telegraph-Image#74]
使用的是nsfwjs api 
![image](https://github.com/user-attachments/assets/edc27935-f9cf-431d-8e9f-921bd80c3243)
上传的几张黄图根本没有识别
![image](https://github.com/user-attachments/assets/4c356877-1980-482a-b879-1d4f462f2385)
手动是正常的
![image](https://github.com/user-attachments/assets/e9cfe976-c20c-4f70-a65d-d1a8cb020348)

**Comment by x-dr** [comment]
![image](https://github.com/user-attachments/assets/81897363-63df-4476-b0fe-97417feae419)

rating值为`-1`是内部请求出错了，RATINGAPI改`https` 协议看看，
