### ISSUE TITLE
[Support] 使用piclist上传的问题

### ISSUE THREAD

**Issue by heichaowo** [x-dr/telegraph-Image#75]
使用自定义设定api地址为x.x/api.tg
通过以上的设定实际山图片已经上传到图床了，但是软件返回上传失败，应该是要输入正确的返回数据地址
![image](https://github.com/user-attachments/assets/1d9124ab-ce86-4dfa-83b8-4db0e3ce212a)
请求作者告知

**Comment by x-dr** [comment]
![](https://img.131213.xyz/file/1027446f7923c593ee0aa.png)

按照这个修改

**Comment by heichaowo** [comment]
搞定啦，谢谢作者
