### ISSUE TITLE
关于telegraph接口用不可用说明

### ISSUE THREAD

**Issue by x-dr** [x-dr/telegraph-Image#81]
[https://telegra.ph/](https://telegra.ph/) 不给上传文件了只能引用外链了

[原文连接](https://x.com/durov/status/1832054680899215647)

![image](https://github.com/user-attachments/assets/27fb616a-c96e-4941-9f56-eee76bc17b94)

**Comment by weiyidu** [comment]
这个方法行的通吗？
https://github.com/cf-pages/Telegraph-Image/issues/178#issuecomment-2334302521

**Comment by mundane799699** [comment]
> 这个方法行的通吗？ [cf-pages/Telegraph-Image#178 (comment)](https://github.com/cf-pages/Telegraph-Image/issues/178#issuecomment-2334302521)

问题是把php部署到哪里？

**Comment by mundane799699** [comment]
> 这个方法行的通吗？ [cf-pages/Telegraph-Image#178 (comment)](https://github.com/cf-pages/Telegraph-Image/issues/178#issuecomment-2334302521)

问题是把php部署到哪里？按他的说法图片应该也是上传到php的那个服务器。但是很多人用这个项目是图它免费的图片存取。如果要自己搞个服务器，何必用这个项目。

**Comment by oplxc** [comment]
> > 这个方法行的通吗？ [cf-pages/Telegraph-Image#178 (comment)](https://github.com/cf-pages/Telegraph-Image/issues/178#issuecomment-2334302521)
> 
> 问题是把php部署到哪里？按他的说法图片应该也是上传到php的那个服务器。但是很多人用这个项目是图它免费的图片存取。如果要自己搞个服务器，何必用这个项目。

可以部署到任何php运行环境，不是只能在服务器是跑，任何虚拟主机php可以。如果真的想撸便宜虚拟主机/免费php空间羊毛，当我没说。
