### ISSUE TITLE
后台登录错误

### ISSUE THREAD

**Issue by mslxq** [x-dr/telegraph-Image#82]
### 使用TG_Channe接口上传失败
使用tencent接口正常

![错误0.png](https://openai-75050.gzc.vod.tencent-cloud.com/openaiassets_5aded52bf529419a6fbe1707cc56fb3f_2579861725667754962.png)

### 后台登录错误

提示信息为：**Unexpected token 'I', "Internal S"... is not valid JSON**

![错误.png](https://openai-75050.gzc.vod.tencent-cloud.com/openaiassets_1804b7fed897a9e8f9d69db65869aac0_2579861725667753955.png)

**Comment by sunwaychan** [comment]
![微信截图_20240907023000](https://github.com/user-attachments/assets/64da9d4e-624c-4aca-a3f5-73dbb8bb7599)
一样只能tencent接口。tg-channel这个就提示上传错误。

**Comment by xiaochenhh** [comment]
tg那边已经关闭接口了，嫖不了了，看官方发的文章说关了

**Comment by libaxuan** [comment]
同！ 求解决方式

**Comment by libaxuan** [comment]
tencent 接口如何配置 谢谢

**Comment by x-dr** [comment]
tg-channel你配置了吗？没配置的话认真看文档重新部署

**Comment by sunwaychan** [comment]
> tg-channel

文档中没提到tg-channel配置，请问在哪里

**Comment by weiyidu** [comment]
> tg-channel你配置了吗？没配置的话认真看文档重新部署

我按照文档操作，channel可以正常上传，但是后台也是这个错误提示。

**Comment by weiyidu** [comment]
> tg-channel你配置了吗？没配置的话认真看文档重新部署

我用的之前那套程序的数据库，没有重建，会不会是这个原因。

**Comment by x-dr** [comment]
> > tg-channel你配置了吗？没配置的话认真看文档重新部署
> 
> 我用的之前那套程序的数据库，没有重建，会不会是这个原因。

不会   我现在用的也是之前的数据库

**Comment by zy111x** [comment]
我也是，tg_channel不能正常上传，Tencent可以，为什么呀，有解决办法吗，完全按照文档操作？

**Comment by x-dr** [comment]
> 我也是，tg_channel不能正常上传，Tencent可以，为什么呀，有解决办法吗，完全按照文档操作？

别人都正常用  你不能正常上传又不贴下配置截图谁能知道你什么问题？

**Comment by zy111x** [comment]
![ae2fe991-e8a4-4d1a-b230-e823a2a0f958](https://github.com/user-attachments/assets/0c7f1760-4ca3-4ba9-b39c-18ada93a17ea)

**Comment by x-dr** [comment]
> ![ae2fe991-e8a4-4d1a-b230-e823a2a0f958](https://private-user-images.githubusercontent.com/150530845/365575718-0c7f1760-4ca3-4ba9-b39c-18ada93a17ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzUyOTcsIm5iZiI6MTcyNTg3NDk5NywicGF0aCI6Ii8xNTA1MzA4NDUvMzY1NTc1NzE4LTBjN2YxNzYwLTRjYTMtNGJhOS1iMzljLTE4YWRhOTNhMTdlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwOTQzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDBmMjNhODc5YmE3MDllZTIzZDFjNmE2NjdiNDY5NGE0ZDdiNDY1Y2ZiYzEzOTc3Y2FkMTljYTlhODZhNzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aSa_KP7D3wK39gcWguFFYKs6bP_bYBJPOwYNRxcBL0s)

环境变量截图看看

**Comment by zy111x** [comment]
![image](https://github.com/user-attachments/assets/21c2ed4c-ce2c-464d-87d9-7532ee2627b4)

**Comment by x-dr** [comment]
> ![image](https://private-user-images.githubusercontent.com/150530845/365684781-21c2ed4c-ce2c-464d-87d9-7532ee2627b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTc2MDEsIm5iZiI6MTcyNTg5NzMwMSwicGF0aCI6Ii8xNTA1MzA4NDUvMzY1Njg0NzgxLTIxYzJlZDRjLWNlMmMtNDY0ZC04N2Q5LTc1MzJlZTI2MjdiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxNTU1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWViNDQwMDRlZDkwMTFmOTYyOTM2ZGU0ZTg0Y2Q0ZDJmYjE2ZGY3OTMxZDAzYWRhYTFmMTEwZTk1NWJhNmVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uK7cxLjaYwfNWMnfv-6OVaQ4Eqo-BvnxqjGWC8B0xWs)

认真看文档  把环境变量都填好

**Comment by zy111x** [comment]
大佬我是小白，请问这些变量都是必须的吗

**Comment by weiyidu** [comment]
> 大佬我是小白，请问这些变量都是必须的吗

BASIC_USER
BASIC_PASS
TG_BOT_TOKEN
TG_CHAT_ID

这四个是必须的

**Comment by zy111x** [comment]
好的明白啦谢谢您

**Comment by zy111x** [comment]
> > ![ae2fe991-e8a4-4d1a-b230-e823a2a0f958](https://private-user-images.githubusercontent.com/150530845/365575718-0c7f1760-4ca3-4ba9-b39c-18ada93a17ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzUyOTcsIm5iZiI6MTcyNTg3NDk5NywicGF0aCI6Ii8xNTA1MzA4NDUvMzY1NTc1NzE4LTBjN2YxNzYwLTRjYTMtNGJhOS1iMzljLTE4YWRhOTNhMTdlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwOTQzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDBmMjNhODc5YmE3MDllZTIzZDFjNmE2NjdiNDY5NGE0ZDdiNDY1Y2ZiYzEzOTc3Y2FkMTljYTlhODZhNzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aSa_KP7D3wK39gcWguFFYKs6bP_bYBJPOwYNRxcBL0s)
> 
> 环境变量截图看看

![image](https://github.com/user-attachments/assets/c1ca8b3a-d335-494d-a07b-b2fe045dc000)
还是不行呀大佬

**Comment by weiyidu** [comment]
> > > ![ae2fe991-e8a4-4d1a-b230-e823a2a0f958](https://private-user-images.githubusercontent.com/150530845/365575718-0c7f1760-4ca3-4ba9-b39c-18ada93a17ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzUyOTcsIm5iZiI6MTcyNTg3NDk5NywicGF0aCI6Ii8xNTA1MzA4NDUvMzY1NTc1NzE4LTBjN2YxNzYwLTRjYTMtNGJhOS1iMzljLTE4YWRhOTNhMTdlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwOTQzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDBmMjNhODc5YmE3MDllZTIzZDFjNmE2NjdiNDY5NGE0ZDdiNDY1Y2ZiYzEzOTc3Y2FkMTljYTlhODZhNzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aSa_KP7D3wK39gcWguFFYKs6bP_bYBJPOwYNRxcBL0s)
> > 
> > 
> > 环境变量截图看看
> 
> ![image](https://private-user-images.githubusercontent.com/150530845/366025804-c1ca8b3a-d335-494d-a07b-b2fe045dc000.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjkyMzksIm5iZiI6MTcyNTk2ODkzOSwicGF0aCI6Ii8xNTA1MzA4NDUvMzY2MDI1ODA0LWMxY2E4YjNhLWQzMzUtNDk0ZC1hMDdiLWIyZmUwNDVkYzAwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMTQ4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGY3ZjNiOGFmZWQ0NWJjOGQ0ZTljODFiZDAwYWI3NGMwMDgzOGUxMDE0ZDE4MmNiYjViOTFjYzdjMjNjNmI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yaUYeeZ2OrcrFzkV5rlzySKOLnFub7is7EmvU5YSSSk) 还是不行呀大佬


tg_chat_id 正确是前面有“-” （减号）你没获取对。
具体看第三步https://github.com/MarSeventh/CloudFlare-ImgBed
变量添加完后重新部署

**Comment by zy111x** [comment]
> > > > ![ae2fe991-e8a4-4d1a-b230-e823a2a0f958](https://private-user-images.githubusercontent.com/150530845/365575718-0c7f1760-4ca3-4ba9-b39c-18ada93a17ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzUyOTcsIm5iZiI6MTcyNTg3NDk5NywicGF0aCI6Ii8xNTA1MzA4NDUvMzY1NTc1NzE4LTBjN2YxNzYwLTRjYTMtNGJhOS1iMzljLTE4YWRhOTNhMTdlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwOTQzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDBmMjNhODc5YmE3MDllZTIzZDFjNmE2NjdiNDY5NGE0ZDdiNDY1Y2ZiYzEzOTc3Y2FkMTljYTlhODZhNzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aSa_KP7D3wK39gcWguFFYKs6bP_bYBJPOwYNRxcBL0s)
> > > 
> > > 
> > > 环境变量截图看看
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/150530845/366025804-c1ca8b3a-d335-494d-a07b-b2fe045dc000.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjkyMzksIm5iZiI6MTcyNTk2ODkzOSwicGF0aCI6Ii8xNTA1MzA4NDUvMzY2MDI1ODA0LWMxY2E4YjNhLWQzMzUtNDk0ZC1hMDdiLWIyZmUwNDVkYzAwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMTQ4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGY3ZjNiOGFmZWQ0NWJjOGQ0ZTljODFiZDAwYWI3NGMwMDgzOGUxMDE0ZDE4MmNiYjViOTFjYzdjMjNjNmI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yaUYeeZ2OrcrFzkV5rlzySKOLnFub7is7EmvU5YSSSk) 还是不行呀大佬
> 
> tg_chat_id 正确是前面有“-” （减号）你没获取对。 具体看第三步https://github.com/MarSeventh/CloudFlare-ImgBed 变量添加完后重新部署

成功！感谢大佬耐心解答（ps:很感动，很少见对小白这么有耐心的人了）
