### ISSUE TITLE
多加一个代理访问

### ISSUE THREAD

**Issue by weiyidu** [x-dr/telegraph-Image#9]
> $imagesUrl['url'][0] = "https://i".rand(0,3).".wp.com/telegra.ph".$response[0]['src'];
$imagesUrl['url'][1] = "https://telegra.ph".$response[0]['src'];
$imagesUrl['url'][2] = "https://images.weserv.nl/?url=".$imagesUrl['url'][1];

**Comment by love2wind** [comment]
wp.com的这个代理失效了吗？
`https://telegra.ph/file/3eece51747b2a01d91d56.png`
![3eece51747b2a01d91d56.png](https://telegra.ph/file/3eece51747b2a01d91d56.png)
`https://i3.wp.com/telegra.ph/file/3eece51747b2a01d91d56.png`
![3eece51747b2a01d91d56.png](https://i3.wp.com/telegra.ph/file/3eece51747b2a01d91d56.png)
代理403了
