### ISSUE TITLE
[Support] 怎么配置PicGo上传图片

### ISSUE THREAD

**Issue by w8541552266** [x-dr/telegraph-Image#91]
<img src="https://tncache1-f1.v3mh.com/image/2024/09/12/66dcef26031d7f18fb7ad3ab659a536a.png"/>

**Comment by x-dr** [comment]
> ![](https://camo.githubusercontent.com/b5ba82c7a6d57c94d2b977bcccbb19db9e57dc4968b99d1dd0d8eabf27550337/68747470733a2f2f746e6361636865312d66312e76336d682e636f6d2f696d6167652f323032342f30392f31322f36366463656632363033316437663138666237616433616236353961353336612e706e67)

https://github.com/x-dr/telegraph-Image/issues/75
