### ISSUE TITLE
tg新接口

### ISSUE THREAD

**Issue by weiyidu** [x-dr/telegraph-Image#92]
在论坛看到的，接口地址：https://telegra.ph/upload?source=bugtracker
![cover](https://pic.jiasu.in/images/1726150129930.png)

**Comment by PoemMistyMoon** [comment]
自己改也可以，/src/app/page.js里面启用tg选项，之前失效后隐藏了 但是没删，然后去/src/app/api/tg/route.js，把原上传链接改成https://telegra.ph/upload?source=bugtracker就行了

**Comment by SokWith** [comment]
接口目前有效

**Comment by x-dr** [comment]
已经改好了

**Comment by SokWith** [comment]
> 已经改好了

似乎链接有时效性，我上午的链接已经失效了。

**Comment by SokWith** [comment]
> > 已经改好了
> 
> 似乎生成链接有时效性，我上午的链接已经失效了。 https://webpho.pages.dev/file/45bbc5a820c70fe76abcd-cd30e2dd4fe83f1dd3.png

果然又失效了。
再给一个测试图片，看看多久失效
![这是图片](https://webpho.pages.dev/file/3ff5fbe74f591e993b63b-1ba5ec95442e5c7f1e.jpg "黎明前")

**Comment by x-dr** [comment]
那我还是改回默认频道图床吧
