### ISSUE TITLE
R2无法使用

### ISSUE THREAD

**Issue by kiko923** [x-dr/telegraph-Image#99]
![ba17e805508283ee433b58a3177bd65](https://github.com/user-attachments/assets/3b505bb2-0dc7-4e9b-99fa-d9ac40fa803f)

**Comment by x-dr** [comment]
截图你的配置看看

**Comment by kiko923** [comment]
> 截图你的配置看看

请问是哪个配置

**Comment by wu73-cmd** [comment]
我是只有58那个接口可以上传
